IF OBJECT_ID('PRESCRICAO_MEDICO') IS NOT NULL
    DROP TABLE dbo.PRESCRICAO_MEDICO;


IF OBJECT_ID('PRESCRICAO_PACIENTE') IS NOT NULL
    DROP TABLE dbo.PRESCRICAO_PACIENTE;


IF OBJECT_ID('PRESCRICAO_FARMACIA') IS NOT NULL
    DROP TABLE dbo.PRESCRICAO_FARMACIA;

IF OBJECT_ID('PRESCRICAO_FARMACEUTICA') IS NOT NULL
    DROP TABLE dbo.PRESCRICAO_FARMACEUTICA;

IF OBJECT_ID('PRESCRICAO_FARMACO') IS NOT NULL 
    DROP TABLE dbo.PRESCRICAO_FARMACO;

IF OBJECT_ID('PRESCRICAO_PRESCRICAO') IS NOT NULL
    DROP TABLE dbo.PRESCRICAO_PRESCRICAO;


IF OBJECT_ID('PRESCRICAO_PRESC_FARMACO') IS NOT NULL
    DROP TABLE dbo.PRESCRICAO_PRESC_FARMACO;





CREATE TABLE PRESCRICAO_MEDICO(
    NUMSNS int ,
    NOME varchar(128) NOT NULL,
    ESPECIALIDADE varchar(128) NOT NULL,
    PRIMARY KEY (NUMSNS),
);

CREATE TABLE PRESCRICAO_PACIENTE(
    NUMUTENTE int NOT NULL,
    NOME varchar(128) NOT NULL,
    DATANASC date NOT NULL,
    ENDERECO varchar(128) NOT NULL,

    PRIMARY KEY (NUMUTENTE),
);


CREATE TABLE PRESCRICAO_FARMACIA(
    NOME varchar(128) NOT NULL,
    TELEFONE int NOT NULL,
    ENDERECO varchar(128) NOT NULL,

    PRIMARY KEY (NOME),
);


CREATE TABLE PRESCRICAO_FARMACEUTICA(
    NUMREG int NOT NULL,
    NOME varchar(128) NOT NULL, 
    ENDERECO varchar(128) NOT NULL,

    PRIMARY KEY (NUMREG),

);

CREATE TABLE PRESCRICAO_FARMACO(
    NUMREGFARM int NOT NULL,
    NOME varchar(128) NOT NULL,
    FORMULA varchar(128) NOT NULL,

    PRIMARY KEY (NOME),
    FOREIGN KEY (NUMREGFARM) REFERENCES PRESCRICAO_FARMACEUTICA(NUMREG),

);


CREATE TABLE PRESCRICAO_PRESCRICAO(
    NUMPRESC int NOT NULL,
    NUMUTENTE int NOT NULL,
    NUMMEDICO int ,
    FARMACIA varchar(128),
    DATAPROC date,

    PRIMARY KEY (NUMPRESC),
    FOREIGN KEY (NUMUTENTE) REFERENCES PRESCRICAO_PACIENTE(NUMUTENTE),
    FOREIGN KEY (NUMMEDICO) REFERENCES PRESCRICAO_MEDICO(NUMSNS),
    FOREIGN KEY (FARMACIA) REFERENCES PRESCRICAO_FARMACIA(NOME),
);


CREATE TABLE PRESCRICAO_PRESC_FARMACO(
    NUMPRESC int NOT NULL,
    NUMREGFARM int NOT NULL,
    NOMEFARMACO varchar(128) NOT NULL,

    PRIMARY KEY(NUMPRESC,NUMREGFARM,NOMEFARMACO),
    FOREIGN KEY (NUMPRESC) REFERENCES PRESCRICAO_PRESCRICAO(NUMPRESC),
    FOREIGN KEY (NUMREGFARM) REFERENCES PRESCRICAO_FARMACEUTICA(NUMREG),
);


