IF OBJECT_ID('GETSTOCK_TIPO_FORNECEDOR', 'U') IS NOT NULL
    DROP TABLE dbo.GETSTOCK_TIPO_FORNECEDOR;


IF OBJECT_ID('GETSTOCK_FORNECEDOR', 'U') IS NOT NULL
    DROP TABLE dbo.GETSTOCK_FORNECEDOR;

IF OBJECT_ID('GETSTOCK_PRODUTO', 'U') IS NOT NULL
    DROP TABLE dbo.GETSTOCK_PRODUTO;

IF OBJECT_ID('GETSTOCK_ENCOMENDA', 'U') IS NOT NULL
    DROP TABLE dbo.GETSTOCK_ENCOMENDA;

IF OBJECT_ID('GETSTOCK_ITEM', 'U') IS NOT NULL
    DROP TABLE dbo.GETSTOCK_ITEM;



--Tabelas

CREATE TABLE GETSTOCK_TIPO_FORNECEDOR(
    CODIGO int NOT NULL,
    DESIGNACAO int NOT NULL,

    PRIMARY KEY (CODIGO),
);


CREATE TABLE GETSTOCK_FORNECEDOR(
    NIF bigint NOT NULL CHECK (NIF > 100000000),
    NOME varchar(128) NOT NULL,
    FAX int NOT NULL,
    ENDERECO varchar(128),
    CONDPAG int NOT NULL,
    TIPO int NOT NULL,

    
    PRIMARY KEY (NIF),
    FOREIGN KEY (TIPO) REFERENCES GETSTOCK_TIPO_FORNECEDOR(CODIGO),
    
);


CREATE  TABLE GETSTOCK_PRODUTO(
    CODIGO int NOT NULL,
    NOME varchar(128) NOT NULL,
    PRECO money NOT NULL,
    IVA int NOT NULL CHECK(IVA>=0 and IVA<=100),
    UNIDADES int NOT NULL,

    PRIMARY KEY (CODIGO),


);


CREATE TABLE GETSTOCK_ENCOMENDA(
    NUMERO int NOT NULL,
    DATA date NOT NULL,
    FORNECEDOR bigint NOT NULL CHECK (FORNECEDOR > 100000000),


    PRIMARY KEY (NUMERO),
    FOREIGN KEY (FORNECEDOR) REFERENCES GETSTOCK_FORNECEDOR(NIF),
);


CREATE TABLE GETSTOCK_ITEM(
    NUMENC int NOT NULL,
    CODPROD int NOT NULL,
    UNIDADES int NOT NULL,

    FOREIGN KEY (NUMENC) REFERENCES GETSTOCK_ENCOMENDA(NUMERO),
    FOREIGN KEY (CODPROD) REFERENCES GETSTOCK_PRODUTO(CODIGO),
);