

IF OBJECT_ID('COMPANY2_DEPARTMENT', 'U') IS NOT NULL
    DROP TABLE dbo.COMPANY2_DEPARTMENT;

IF OBJECT_ID('COMPANY2_EMPLOYEE', 'U') IS NOT NULL
    DROP TABLE dbo.COMPANY2_EMPLOYEE;

IF OBJECT_ID('COMPANY2_DEPENDENT', 'U') IS NOT NULL
    DROP TABLE dbo.COMPANY2_DEPENDENT;


IF OBJECT_ID('COMPANY2_DEPT_LOCATIONS', 'U') IS NOT NULL
    DROP TABLE dbo.COMPANY2_DEPT_LOCATIONS;

IF OBJECT_ID('COMPANY2_PROJECT', 'U') IS NOT NULL
    DROP TABLE dbo.COMPANY2_PROJECT;

IF OBJECT_ID('COMPANY2_WORKS_ON', 'U') IS NOT NULL
    DROP TABLE dbo.COMPANY2_WORKS_ON;



--Tabelas

CREATE TABLE COMPANY2_EMPLOYEE (
    FNAME varchar(128) not NULL,
	MINIT CHAR(128) not NULL,
    LNAME varchar(128) not NULL,
    SSN int not NULL CHECK (SSN >0), 
    BDATE date not NULL,
    ADDRESS varchar(128) not NULL,
    SEX char(1) not NULL CHECK (SEX='F'OR SEX='M'),
    SALARY int not NULL,
    SUPERSSN int CHECK (SUPERSSN > 0),
    DNO int NOT NULL,

    PRIMARY KEY (SSN),
    FOREIGN KEY (SUPERSSN) REFERENCES COMPANY2_EMPLOYEE(SSN),
    
);
CREATE Table COMPANY2_DEPARTMENT (
    DNAME varchar(128) not NULL,
    DNUMBER int not NULL,
    MGRSSN int CHECK (MGRSSN > 0),
    MGRSTARTDATE date,

    PRIMARY KEY (DNUMBER),
	FOREIGN KEY (MGRSSN) REFERENCES COMPANY2_EMPLOYEE(SSN),
    
);



CREATE Table COMPANY2_DEPT_LOCATIONS (
    DNUMBER int not NULL,
    DLOCATION varchar(128) not NULL,

    PRIMARY KEY (DNUMBER, DLOCATION),
    FOREIGN KEY (DNUMBER) REFERENCES COMPANY2_DEPARTMENT(DNUMBER),

);

CREATE Table COMPANY2_PROJECT (
    PNAME varchar(128) not NULL,
    PNUMBER int not NULL,
    PLOCATION varchar(128) not NULL,
    DNUM int not NULL,

    PRIMARY KEY (PNUMBER),
    FOREIGN KEY (DNUM) REFERENCES COMPANY2_DEPARTMENT(DNUMBER),
);


CREATE Table COMPANY2_WORKS_ON (
    ESSN int NOT NULL CHECK (ESSN > 0),
    PNO int NOT NULL,
    HOURS int ,
	
	PRIMARY KEY (ESSN,PNO),
    Foreign KEY (ESSN) REFERENCES COMPANY2_EMPLOYEE(SSN),
    Foreign KEY (PNO) REFERENCES COMPANY2_PROJECT(PNUMBER),
);

CREATE TABLE COMPANY2_DEPENDENT (
    ESSN int NOT NULL CHECK (ESSN > 0),
    DEPENDENT_NAME varchar(128) not NULL,
    SEX varchar(1) NOT NULL CHECK (SEX='F'OR SEX='M'),
    BDATE date NOT NULL,
    RELATIONSHIP varchar(128) NOT NULL,

    PRIMARY KEY (ESSN,DEPENDENT_NAME),
    FOREIGN KEY (ESSN) REFERENCES COMPANY2_EMPLOYEE(SSN),

);





