
-----NOTA IMPORTANTE-----
--- HOUVE ERROS AO REALIZAR O EXERCÍCIO DA AULA 3 
-- ASSOCIADO A ESTE TEMA É PRECISO VISUALIZAR O EXERCÍCIO DA
-- AULA 2 ASSOCIADO A ESTE TENA PARA COMPLETAR ESTE EXERCÍCIO

IF OBJECT_ID('CONFERENCIA_NAO_ESTUDANTE', 'U') IS NOT NULL
	DROP TABLE dbo.CONFERENCIA_NAO_ESTUDANTE;
IF OBJECT_ID('CONFERENCIA_ESTUDANTE', 'U') IS NOT NULL
	DROP TABLE dbo.CONFERENCIA_NAO_ESTUDANTE;
IF OBJECT_ID('CONFERENCIA_PARTICIPANTE', 'U') IS NOT NULL
	DROP TABLE dbo.CONFERENCIA_PARTICIPANTE;
IF OBJECT_ID('CONFERENCIA_AUTOR', 'U') IS NOT NULL
	DROP TABLE dbo.CONFERENCIA_AUTOR;
IF OBJECT_ID('CONFERENCIA_TEM_ARTIGO_PESSOA', 'U') IS NOT NULL
	DROP TABLE dbo.CONFERENCIA_TEM_ARTIGO_PESSOA;
IF OBJECT_ID('CONFERENCIA_INSTITUICAO', 'U') IS NOT NULL
	DROP TABLE dbo.CONFERENCIA_INSTITUICAO;
IF OBJECT_ID('CONFERENCIA_TEM_CONFERENCIA_ARTIGO', 'U') IS NOT NULL
	DROP TABLE dbo.CONFERENCIA_TEM_CONFERENCIA_ARTIGO;
IF OBJECT_ID('CONFERENCIA_PESSOA', 'U') IS NOT NULL
	DROP TABLE dbo.CONFERENCIA_PESSOA;
IF OBJECT_ID('CONFERENCIA_ARTIGO', 'U') IS NOT NULL
	DROP TABLE dbo.CONFERENCIA_ARTIGO;
IF OBJECT_ID('CONFERENCIA_CONFERENCIA', 'U') IS NOT NULL
	DROP TABLE dbo.CONFERENCIA_CONFERENCIA;

CREATE TABLE CONFERENCIA_CONFERENCIA (
    ID int NOT NULL,    
    PRIMARY KEY (ID)
);

CREATE TABLE CONFERENCIA_ARTIGO (
    ID int NOT NULL,
    TITULO varchar(128) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE CONFERENCIA_PESSOA (
    EMAIL varchar(128) NOT NULL,
    NOME varchar(128) NOT NULL,
    PRIMARY KEY (EMAIL)
);

CREATE TABLE CONFERENCIA_TEM_CONFERENCIA_ARTIGO (
    AID int NOT NULL,
    CID int NOT NULL,
    FOREIGN KEY (AID) REFERENCES CONFERENCIA_ARTIGO(ID),
    FOREIGN KEY(CID) REFERENCES CONFERENCIA_CONFERENCIA(ID)
);

CREATE TABLE CONFERENCIA_INSTITUICAO (
    NOME varchar(128) NOT NULL,
    ENDERECO varchar(128) NOT NULL,
    PEMAIL varchar(128) NOT NULL,
    FOREIGN KEY (PEMAIL) REFERENCES CONFERENCIA_PESSOA(EMAIL),
    PRIMARY KEY (NOME)
);

CREATE TABLE CONFERENCIA_TEM_ARTIGO_PESSOA(
    AID int NOT NULL,
    PEMAIL varchar(128) NOT NULL,
    FOREIGN KEY (AID) REFERENCES CONFERENCIA_ARTIGO(ID),
    FOREIGN KEY (PEMAIL) REFERENCES CONFERENCIA_PESSOA(EMAIL)
);

CREATE TABLE CONFERENCIA_AUTOR (
    EMAIL varchar(128) NOT NULL,
    FOREIGN KEY (EMAIL) REFERENCES CONFERENCIA_PESSOA(EMAIL),
    PRIMARY KEY (EMAIL)
);

CREATE TABLE CONFERENCIA_PARTICIPANTE (
    EMAIL varchar(128) NOT NULL,
    [DATA] date NOT NULL,
    MORADA varchar(128) NOT NULL,
    CID int NOT NULL,
    FOREIGN KEY(EMAIL) REFERENCES CONFERENCIA_PESSOA(EMAIL),
    FOREIGN KEY(CID) REFERENCES CONFERENCIA_CONFERENCIA(ID),
    PRIMARY KEY (EMAIL, CID)
);

CREATE TABLE CONFERENCIA_ESTUDANTE (
    EMAIL varchar(128) NOT NULL,
    [DATA] date NOT NULL,
    MORADA varchar(512) NOT NULL,
    CID int NOT NULL,
    COMPROVATIVO varchar(128) NOT NULL,
    FOREIGN KEY (EMAIL, CID) REFERENCES CONFERENCIA_PARTICIPANTE(EMAIL, CID),
    PRIMARY KEY (EMAIL)
);

CREATE TABLE CONFERENCIA_NAO_ESTUDANTE (
    EMAIL varchar(128) NOT NULL,
    [DATA] date NOT NULL,
    MORADA varchar(512) NOT NULL,
    CID int NOT NULL,
    TRANSACAO varchar(128) NOT NULL,
    FOREIGN KEY (EMAIL, CID) REFERENCES CONFERENCIA_PARTICIPANTE(EMAIL, CID),
    PRIMARY KEY (EMAIL)
);